### ISSUE TITLE
Removing Textscreens hooks results in large bugs with other addons

### ISSUE THREAD

**Issue by Cherry** [MalboroDEV/PermaProps#22]
These lines are removing my hooks that prevent other tools from interfacing with Textscreens:

https://github.com/MalboroDEV/PermaProps/blob/master/lua/permaprops/sv_permissions.lua#L75-L76

This causes problems in servers as it allows users to run things like Fading Doors on Textscreens, resulting in the bug reported at https://github.com/Cherry/3D2D-Textscreens/issues/60#issuecomment-568050577 and making its rounds amongst some [popular YouTubers](https://www.youtube.com/watch?v=wo3lGwRID80) right now.

I've added `permaprops` to the whitelist of tools able to run on Textscreens as per https://github.com/Cherry/3D2D-Textscreens/commit/870b17e12272f2bc6d99fcaf2c4ef5c12027fa2d, so please update and release a new version of this addon ASAP. Brute-force removal of my hooks is causing lots of problems.

**Comment by MalboroDEV** [comment]
Sending steam update asap.
