### ISSUE TITLE
Certain props/vehicles break on using perma prop

### ISSUE THREAD

**Issue by deadspidervenom** [MalboroDEV/PermaProps#23]
the main addon i mean is "SligWolf's Bus and BendyBus" on use on their bus stops, the bus stops lose their chairs.

On saving vehicles set to have no owner in darkrp, it resets them to have a owner.

On saving a prop that is able to be bought by "[Blackberry] Minimalistic Inventory System" the prop loses the ability to be bought.

**Comment by MalboroDEV** [comment]
I let you take a look into `sv_specialfcn.lua`, you can code customs checks with your entity.
