### ISSUE TITLE
Adv Duplicator 2 Support? 

### ISSUE THREAD

**Issue by Servius** [MalboroDEV/PermaProps#24]
Hi. 

I guess this a two way issue now. Wondering if the Perma Props and AdvDupe2 teams could collaborate together to make the following possible: 

> Would like the ability to copy world props when enabled. I accidentally had a good chunk of work perma propped before remembering to dupe. Im sure this has happened to others as well.

I posted an issue here over on their corresponding repository. Hoping youd have some ideas on how to approach the problem. 

https://github.com/wiremod/advdupe2/issues/281

**Comment by dannyhpy** [comment]
> Looks like its due to the props being prop_dynamic which are uncopyable. You can delete the line, https://github.com/MalboroDEV/PermaProps/blob/46e628b68ef0b8f9ebb5b870c63387cfc1f2d38c/lua/permaprops/sv_lib.lua#L97 and see if they can be copied after that.

Did you try this fix?
