### ISSUE TITLE
Permaprop not showing at map load/server starting

### ISSUE THREAD

**Issue by Hexon-Boi** [MalboroDEV/PermaProps#28]
This started happening few days ago. I don't know what to do. I didn't do anything that should cause this
Props saved before load normally
Props saved after load only after cleanup/Permaprop Reload

Any help?

Before Cleanup/Reload
![obraz](https://user-images.githubusercontent.com/70663961/92034942-451dfc80-ed6e-11ea-978c-d03796edd76a.png)
After Cleanup/Reload
![obraz](https://user-images.githubusercontent.com/70663961/92035245-b3fb5580-ed6e-11ea-8cef-d7489c4e366a.png)

**Comment by MalboroDEV** [comment]
The loading Hook isn't called ... Maybe something is blocking it

**Comment by Hexon-Boi** [comment]
Okay, thanks! That solved my problem :)
