### ISSUE TITLE
Wiremod Support

### ISSUE THREAD

**Issue by Peekofwar** [MalboroDEV/PermaProps#37]
As it stands right now, all Wiremod entities loose their data when you save them to the PermaProps database. This also results in some script errors when you try to use a loaded Wiremod entity, such as a button.

Also, when saving a prop that a Wiremod entity is attached to, the Wiremod entity is removed.

```
[Wiremod] lua/entities/gmod_wire_button.lua:181: attempt to concatenate local 'value' (a nil value)
  1. ShowOutput - lua/entities/gmod_wire_button.lua:181
   2. Switch - lua/entities/gmod_wire_button.lua:157
    3. unknown - lua/entities/gmod_wire_button.lua:98


[Wiremod] lua/entities/gmod_wire_button.lua:181: attempt to concatenate local 'value' (a nil value)
  1. ShowOutput - lua/entities/gmod_wire_button.lua:181
   2. Switch - lua/entities/gmod_wire_button.lua:163
    3. unknown - lua/entities/gmod_wire_button.lua:111
```

**Comment by MalboroDEV** [comment]
PermaProps doesn't support WireMod by default.
If you want import it, just take a look into : permaprops/lua/permaprops/sv_specialfcn.lua
