### ISSUE TITLE
PermaProps Issue

### ISSUE THREAD

**Issue by dhkatz** [MalboroDEV/PermaProps#4]
Been noticing this error popup a bit more frequently lately

`[ERROR] workshop/lua/permaprops/sv_menu.lua:55: attempt to call method 'IsAdmin' (a nil value)
1. unknown - workshop/lua/permaprops/sv_menu.lua:55
   1. unknown - lua/includes/modules/concommand.lua:54`

**Comment by MalboroDEV** [comment]
Fixed
