### ISSUE TITLE
[ERROR] workshop/lua/permaprops/sv_lib.lua:200: attempt to call method 'IsUserGroup' (a nil value)

### ISSUE THREAD

**Issue by ghost** [MalboroDEV/PermaProps#5]
1. IsAdmin - workshop/lua/permaprops/sv_lib.lua:200
   1. unknown - workshop/lua/permaprops/sv_menu.lua:55
   2. unknown - lua/includes/modules/concommand.lua:54

ServerLog: [FAdmin] MGaming Network -Busy (STEAM_0:1:74659386) Attempted to use tool permaprops

[ERROR] workshop/lua/permaprops/sv_lib.lua:200: attempt to call method 'IsUserGroup' (a nil value)
1. IsAdmin - workshop/lua/permaprops/sv_lib.lua:200
   1. unknown - workshop/lua/permaprops/sv_menu.lua:55
   2. unknown - lua/includes/modules/concommand.lua:54

ServerLog: [FAdmin] MGaming Network -Busy (STEAM_0:1:74659386) Attempted to use tool permaprops

[ERROR] workshop/lua/permaprops/sv_lib.lua:200: attempt to call method 'IsUserGroup' (a nil value)
1. IsAdmin - workshop/lua/permaprops/sv_lib.lua:200
   1. unknown - workshop/lua/permaprops/sv_menu.lua:55
   2. unknown - lua/includes/modules/concommand.lua:54

**Comment by MalboroDEV** [comment]
Fixed
